apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hospital-net-ca-tools
  namespace: hospital-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: hospital-net-ca-tools
  chart:
    git: ssh://git@github.com/kawthers/blockchain-automation-framework.git
    ref: master
    path: platforms/hyperledger-fabric/charts/catools
  values:
    metadata:
      namespace: hospital-net
      name: ca-tools

    replicaCount: 1

    image:
      repository: hyperledger/fabric-ca-tools
      tag: 1.2.1
      pullPolicy: IfNotPresent
      
    storage:
      storageclassname: hospitalsc
      storagesize: 512Mi
