apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: peer0-insurance-cli
  namespace: insurance-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: peer0-insurance-cli
  chart:
    git: ssh://git@github.com/kawthers/blockchain-automation-framework.git
    ref: develop
    path: platforms/hyperledger-fabric/charts/fabric_cli    
  values:
    metadata:
      namespace: insurance-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/wmcgroup777/alpine-utils:1.0
    storage:
      class: insurancesc
      size: 256Mi
    vault:
      role: vault-role
      address: https://vault.bfs-network.name:8200
      authpath: insurance-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/insurance-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/insurance-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    peer:
      name: peer0
      localmspid: insuranceMSP
      tlsstatus: true
      address: peer0.insurance-net.ambassador1.bfs-network.name:8443
    orderer:
      address: orderer1.bfs-net:7050
