apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: channel-hospital-allchannel
  namespace: hospital-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: channel-hospital-allchannel
  chart:
    git: ssh://git@github.com/kawthers/blockchain-automation-framework.git
    ref: develop
    path: platforms/hyperledger-fabric/charts/create_channel   
  values:
    metadata:
      namespace: hospital-net
      network:
        version 2.2.0
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/wmcgroup777/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.hospital-net:7051
      localmspid: hospitalMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: https://vault.bfs-network.name:8200
      authpath: hospital-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/hospital-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/hospital-net/orderer 
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel
    orderer:
      address: orderer1.bfs-net:7050
    channeltx: |-
      Cs0DChgKFggCGgYI0ZWVgQYiCmFsbGNoYW5uZWwSsAMKrQMKCmFsbGNoYW5uZWwSRBIyCgtBcHBs
      aWNhdGlvbhIjEg8KC2hvc3BpdGFsTVNQEgASEAoMaW5zdXJhbmNlTVNQEgAaDgoKQ29uc29ydGl1
      bRIAGtgCErQCCgtBcHBsaWNhdGlvbhKkAggBEhAKDGluc3VyYW5jZU1TUBIAEg8KC2hvc3BpdGFs
      TVNQEgAaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucyIiCgdSZWFkZXJzEhcS
      DQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlu
      cyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIsCgtFbmRvcnNlbWVudBIdEhMI
      AxIPCgtFbmRvcnNlbWVudBACGgZBZG1pbnMiNQoUTGlmZWN5Y2xlRW5kb3JzZW1lbnQSHRITCAMS
      DwoLRW5kb3JzZW1lbnQQAhoGQWRtaW5zKgZBZG1pbnMaHwoKQ29uc29ydGl1bRIREg8KDUJGU0Nv
      bnNvcnRpdW0=