apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: approve-hospital-allchannel-bills1
  namespace: hospital-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: approve-hospital-allchannel-bills1
  chart:
    git: ssh://git@github.com/kawthers/blockchain-automation-framework.git
    ref: master
    path: platforms/hyperledger-fabric/charts/approve_chaincode
  values:
    metadata:
      namespace: hospital-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/wmcgroup777/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.hospital-net:7051
      localmspid: hospitalMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: https://vault.bfs-network.name:8200
      authpath: hospital-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/hospital-net/users/admin 
      orderersecretprefix: secret/crypto/peerOrganizations/hospital-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer1.bfs-net:7050
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.0
      name: bills
      version: 1
      commitarguments: '"initBill","test","1","2","3","4","5"'
      endorsementpolicies:  ''
    channel:
      name: allchannel
