apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-insurance
  namespace: insurance-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-insurance
  chart:
    git: ssh://git@github.com/kawthers/blockchain-automation-framework.git
    ref: master
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: insurance-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/wmcgroup777/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.insurance-net.ambassador1.bfs-network.name:8443
      localmspid: insuranceMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: https://vault.bfs-network.name:8200
      authpath: insurance-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/insurance-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/insurance-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer1.bfs-net:7050
    anchorstx: |-
      CtsCChgKFggCGgYI76qrgQYiCmFsbGNoYW5uZWwSvgIKuwIKCmFsbGNoYW5uZWwSZRJjCgtBcHBs
      aWNhdGlvbhJUCAESUAoMaW5zdXJhbmNlTVNQEkAaBwoDTVNQEgAiDwoLRW5kb3JzZW1lbnQSACIL
      CgdSZWFkZXJzEgAiCwoHV3JpdGVycxIAIgoKBkFkbWlucxIAGsUBEsIBCgtBcHBsaWNhdGlvbhKy
      AQgBEq0BCgxpbnN1cmFuY2VNU1ASnAEIARpQCgtBbmNob3JQZWVycxJBEjcKNQowcGVlcjAuaW5z
      dXJhbmNlLW5ldC5hbWJhc3NhZG9yMS5iZnMtbmV0d29yay5uYW1lEPtBGgZBZG1pbnMaBwoDTVNQ
      EgAiCgoGQWRtaW5zEgAiDwoLRW5kb3JzZW1lbnQSACILCgdSZWFkZXJzEgAiCwoHV3JpdGVycxIA
      KgZBZG1pbnM=

