apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: chaincode-install-insurance-peer0-1
  namespace: insurance-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: chaincode-install-insurance-peer0-1
  chart:
    git: ssh://git@github.com/kawthers/blockchain-automation-framework.git
    ref: develop
    path: platforms/hyperledger-fabric/charts/install_chaincode
  values:
    metadata:
      namespace: insurance-net
      network:
        version: 2.2.0
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/wmcgroup777/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.insurance-net:7051
      localmspid: insuranceMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: https://vault.bfs-network.name:8200
      authpath: insurance-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/insurance-net/users/admin 
      orderersecretprefix: secret/crypto/peerOrganizations/insurance-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretgitprivatekey: secret/credentials/insurance-net/git?git_password
      tls: false
    orderer:
      address: orderer1.ambassador.bfs-network.name:8443
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.0
      name: bills
      version: 1
      lang: node
      maindirectory: v1
      repository:
        hostname: "github.com"
        git_username: "maximusGit"
        url: github.com/kawthers/blockchain-automation-framework.git
        branch: develop
        path: chaincode
      endorsementpolicies:  ''
