apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: insurance-net-ca
  namespace: insurance-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: insurance-net-ca
  chart:
    git: ssh://git@github.com/kawthers/blockchain-automation-framework.git
    ref: master
    path: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: insurance-net
      images:
        alpineutils: index.docker.io/wmcgroup777/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
    server:
      name: ca
      tlsstatus: true
      admin: insurance-admin
    storage:
      storageclassname: insurancesc
      storagesize: 512Mi
    vault:
      role: vault-role
      address: https://vault.bfs-network.name:8200
      authpath: insurance-net-auth
      secretcert: secret/crypto/peerOrganizations/insurance-net/ca?ca.insurance-net-cert.pem
      secretkey: secret/crypto/peerOrganizations/insurance-net/ca?insurance-net-CA.key
      secretadminpass: secret/credentials/insurance-net/ca/insurance?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: haproxy
      type: peer
